# Generated by Django 2.1.7 on 2019-06-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='porterrorfixrecord',
            name='claim',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='porterrorfixrecord',
            name='problem_type',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
