# Generated by Django 2.1.7 on 2019-03-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortErrorDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=30)),
                ('nowCRC', models.IntegerField()),
                ('nowIpv4HeaderError', models.IntegerField()),
                ('everCRC', models.IntegerField()),
                ('everIpv4HeaderError', models.IntegerField()),
                ('stateCRC', models.CharField(choices=[('increase', 'INCREASING'), ('fair', 'fair')], max_length=20)),
                ('stateIpv4HeadError', models.CharField(choices=[('increase', 'INCREASING'), ('fair', 'fair')], max_length=20)),
                ('record_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-record_time'],
            },
        ),
    ]
