# Generated by Django 2.1.7 on 2019-03-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_porterrordiff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortErrorDiff',
        ),
    ]
