# Generated by Django 2.1.7 on 2019-05-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_delete_porterrordiff'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneWayDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=40)),
                ('port_status', models.CharField(max_length=10)),
                ('port_phy_status', models.CharField(max_length=10)),
                ('port_des', models.CharField(max_length=255)),
                ('record_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-record_time'],
            },
        ),
    ]
