# Generated by Django 2.1.7 on 2019-05-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_auto_20190524_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortErrorDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=40)),
                ('nowCRC', models.IntegerField()),
                ('nowIpv4HeaderError', models.IntegerField()),
                ('everCRC', models.IntegerField()),
                ('everIpv4HeaderError', models.IntegerField()),
                ('stateCRC', models.FloatField()),
                ('stateIpv4HeadError', models.FloatField()),
                ('record_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='porterrordiff',
            index=models.Index(fields=['device_name'], name='inspection__device__84792d_idx'),
        ),
    ]
