# Generated by Django 2.1.7 on 2019-06-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_natpoolusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natpoolusage',
            name='device1_nat_usage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='natpoolusage',
            name='device2_nat_usage',
            field=models.FloatField(),
        ),
    ]
