# Generated by Django 2.1.7 on 2019-07-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_auto_20190616_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneWayDeviceFixRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(max_length=40, null=True)),
                ('problem_detail', models.TextField(null=True)),
                ('begin_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('worker', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('claim', models.BooleanField(default=True)),
                ('device_name', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
