# Generated by Django 2.1.7 on 2019-05-29 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspection', '0006_auto_20190529_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortErrorFixRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(max_length=40)),
                ('problem_detail', models.TextField()),
                ('begin_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inspection.PortErrorDiff')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
