# Generated by Django 2.1.7 on 2019-07-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_onewaydevicefixrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneWayDeviceFixRecord',
        ),
    ]
