# Generated by Django 2.1.7 on 2019-05-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_porterrorfixrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porterrordiff',
            name='record_time',
            field=models.DateTimeField(),
        ),
    ]
