# Generated by Django 2.1.7 on 2019-08-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_delete_onewaydevicefixrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneWayDeviceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=40)),
                ('delay_count', models.PositiveSmallIntegerField(null=True)),
                ('tag', models.CharField(max_length=10)),
                ('tag_user', models.CharField(max_length=100)),
                ('tag_time', models.DateTimeField()),
            ],
        ),
    ]
