# Generated by Django 2.2.5 on 2019-10-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0009_onewaydevicetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPingTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_device', models.CharField(max_length=255)),
                ('target_device', models.CharField(max_length=255)),
                ('target_ip', models.GenericIPAddressField()),
                ('loss', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('record_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'MQ_REC_link_ping_test',
            },
        ),
    ]
