# Generated by Django 2.2.5 on 2019-10-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0010_linkpingtest'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='onewaydevice',
            name='inspection__device__8dba78_idx',
        ),
        migrations.RemoveIndex(
            model_name='onewaydevice',
            name='inspection__port_f434c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='porterrordiff',
            name='inspection__device__84792d_idx',
        ),
        migrations.RemoveIndex(
            model_name='porterrordiff',
            name='inspection__port_885f82_idx',
        ),
        migrations.RemoveIndex(
            model_name='portperf',
            name='inspection__device__1efd93_idx',
        ),
        migrations.RemoveIndex(
            model_name='portperf',
            name='inspection__port_a20512_idx',
        ),
        migrations.AddIndex(
            model_name='onewaydevice',
            index=models.Index(fields=['device_name'], name='OM_REP_onew_device__2e9ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='onewaydevice',
            index=models.Index(fields=['port'], name='OM_REP_onew_port_96614a_idx'),
        ),
        migrations.AddIndex(
            model_name='porterrordiff',
            index=models.Index(fields=['device_name'], name='OM_REP_port_device__92ae42_idx'),
        ),
        migrations.AddIndex(
            model_name='porterrordiff',
            index=models.Index(fields=['port'], name='OM_REP_port_port_acbab6_idx'),
        ),
        migrations.AddIndex(
            model_name='portperf',
            index=models.Index(fields=['device_name'], name='OM_REC_port_device__c27f05_idx'),
        ),
        migrations.AddIndex(
            model_name='portperf',
            index=models.Index(fields=['port'], name='OM_REC_port_port_bcbc72_idx'),
        ),
        migrations.AlterModelTable(
            name='linkpingtest',
            table='OM_REP_ping_test',
        ),
        migrations.AlterModelTable(
            name='natpoolusage',
            table='OM_REC_nat_pool_usage',
        ),
        migrations.AlterModelTable(
            name='onewaydevice',
            table='OM_REP_oneway_device',
        ),
        migrations.AlterModelTable(
            name='opticalmoudlediff',
            table='OM_REP_optical_moudle_diff',
        ),
        migrations.AlterModelTable(
            name='porterrordiff',
            table='OM_REP_port_error_diff',
        ),
        migrations.AlterModelTable(
            name='porterrorfixrecord',
            table='OM_REC_port_error_fix_record',
        ),
        migrations.AlterModelTable(
            name='portperf',
            table='OM_REC_port_perf',
        ),
    ]
