# Generated by Django 2.2.5 on 2019-10-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0011_auto_20191028_0943'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onewaydevicetag',
            table='OM_REC_oneway_device_tag',
        ),
    ]
