# Generated by Django 2.2.5 on 2019-10-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0012_auto_20191028_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortErrorFullRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=40)),
                ('crc', models.IntegerField()),
                ('ipv4_head', models.IntegerField()),
                ('record_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'OM_REC_port_error_record',
                'ordering': ['-record_time'],
            },
        ),
    ]
