# Generated by Django 2.2.5 on 2019-11-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0014_linkpinghouraggregate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPingCostStepAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField()),
                ('link_cnt', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'OM_REP_ping_cost_step_aggregate',
            },
        ),
    ]
