# Generated by Django 2.1.5 on 2019-03-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicIpRecord',
            fields=[
                ('device_ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=255)),
                ('logic_port', models.CharField(max_length=40)),
                ('svlan', models.CharField(max_length=30)),
                ('cvlan', models.CharField(max_length=30)),
                ('ip_description', models.TextField(blank=True)),
                ('record_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-record_time', 'device_ip'],
            },
        ),
    ]
