# Generated by Django 2.1.7 on 2019-06-01 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_func', models.CharField(choices=[('BK', 'backup'), ('XM1_0', 'exam_home_user_amount'), ('XM1_1', 'exam_otv_user_amount'), ('XM1_2', 'exam_ims_amount'), ('XM1_3', 'exam_itms_amount'), ('XM2_0', 'exam_cpu_perf'), ('XM2_1', 'exam_memory_perf'), ('XM2_2', 'exam_home_user_ippool'), ('SH', 'show'), ('OTH', 'others')], max_length=20)),
                ('cmd_content', models.TextField()),
                ('cmd_description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('device_ip', models.GenericIPAddressField()),
                ('device_network', models.CharField(max_length=100)),
                ('login_port', models.SmallIntegerField()),
                ('login_user', models.CharField(max_length=30)),
                ('login_password', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['device_ip'],
            },
        ),
        migrations.CreateModel(
            name='DeviceManufactor',
            fields=[
                ('manufactor_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='device_manufactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='watchdog.DeviceManufactor'),
        ),
        migrations.AddField(
            model_name='commandline',
            name='cmd_manufactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='watchdog.DeviceManufactor'),
        ),
    ]
