# Generated by Django 2.1.7 on 2019-03-13 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchdog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicIpAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ies', models.CharField(blank=True, max_length=20)),
                ('order_num', models.CharField(blank=True, max_length=255)),
                ('client_num', models.CharField(max_length=100)),
                ('product_num', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('mask', models.SmallIntegerField()),
                ('gateway', models.CharField(max_length=100)),
                ('link_tag', models.SmallIntegerField()),
                ('device_name', models.CharField(max_length=255)),
                ('logic_port', models.CharField(max_length=40)),
                ('svlan', models.CharField(max_length=30)),
                ('cvlan', models.CharField(max_length=30)),
                ('access_type', models.CharField(blank=True, max_length=10)),
                ('olt_name', models.CharField(blank=True, max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('ip_description', models.TextField(blank=True)),
                ('up_brandwidth', models.SmallIntegerField()),
                ('down_brandwidth', models.SmallIntegerField()),
                ('alc_time', models.DateTimeField(auto_now_add=True)),
                ('adj_order', models.CharField(blank=True, max_length=255)),
                ('adj_time', models.DateTimeField(blank=True)),
                ('close_order', models.CharField(blank=True, max_length=255)),
                ('close_time', models.DateTimeField(blank=True)),
                ('adj_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plcip_adj_user', to=settings.AUTH_USER_MODEL)),
                ('alc_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plcip_alc_user', to=settings.AUTH_USER_MODEL)),
                ('close_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plcip_close_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['alc_time'],
            },
        ),
    ]
