# Generated by Django 2.1.7 on 2019-02-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandline',
            options={'ordering': ['id']},
        ),
    ]
