# Generated by Django 2.1.7 on 2019-03-13 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0002_publicipallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicipallocation',
            name='access_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='publicipallocation',
            name='adj_order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publicipallocation',
            name='adj_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plcip_adj_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicipallocation',
            name='close_order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publicipallocation',
            name='close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicipallocation',
            name='close_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plcip_close_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicipallocation',
            name='ies',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publicipallocation',
            name='ip_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicipallocation',
            name='olt_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publicipallocation',
            name='order_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publicipallocation',
            name='up_brandwidth',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
