# Generated by Django 2.1.7 on 2019-03-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0003_auto_20190313_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicipallocation',
            name='adj_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
