# Generated by Django 2.1.7 on 2019-03-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0005_privateipallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateipallocation',
            name='community',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
