# Generated by Django 2.1.7 on 2019-03-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0006_auto_20190314_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicipallocation',
            name='link_tag',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
