# Generated by Django 2.1.7 on 2019-03-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0007_auto_20190323_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicipallocation',
            name='cvlan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
