# Generated by Django 2.1.7 on 2019-04-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0009_publicipgateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicipallocation',
            name='alc_time',
            field=models.DateTimeField(),
        ),
    ]
