# Generated by Django 2.1.7 on 2019-04-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0010_auto_20190401_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicipallocation',
            name='adj_order',
        ),
        migrations.RemoveField(
            model_name='publicipallocation',
            name='adj_time',
        ),
        migrations.RemoveField(
            model_name='publicipallocation',
            name='adj_user',
        ),
        migrations.RemoveField(
            model_name='publicipallocation',
            name='close_order',
        ),
        migrations.RemoveField(
            model_name='publicipallocation',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='publicipallocation',
            name='close_user',
        ),
        migrations.AddField(
            model_name='publicipallocation',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
