# Generated by Django 2.1.7 on 2019-04-01 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchdog', '0011_auto_20190401_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicIpModRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_order', models.CharField(max_length=255)),
                ('msg', models.TextField()),
                ('record_time', models.DateTimeField()),
                ('mod_target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='watchdog.PublicIpAllocation')),
                ('mod_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plcip_mod_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['record_time'],
            },
        ),
    ]
