# Generated by Django 2.1.7 on 2019-04-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0013_auto_20190401_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicipallocation',
            options={'ordering': ['-alc_time']},
        ),
        migrations.RenameField(
            model_name='publicipmodrecord',
            old_name='msg',
            new_name='mod_msg',
        ),
        migrations.AlterField(
            model_name='publicipmodrecord',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
