# Generated by Django 2.1.7 on 2019-04-01 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchdog', '0014_auto_20190401_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateIpModRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_order', models.CharField(max_length=255)),
                ('mod_msg', models.TextField()),
                ('record_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-record_time'],
            },
        ),
        migrations.RemoveField(
            model_name='privateipallocation',
            name='adj_order',
        ),
        migrations.RemoveField(
            model_name='privateipallocation',
            name='adj_time',
        ),
        migrations.RemoveField(
            model_name='privateipallocation',
            name='adj_user',
        ),
        migrations.RemoveField(
            model_name='privateipallocation',
            name='close_order',
        ),
        migrations.RemoveField(
            model_name='privateipallocation',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='privateipallocation',
            name='close_user',
        ),
        migrations.AddField(
            model_name='privateipallocation',
            name='state',
            field=models.CharField(default='InUse', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicipallocation',
            name='state',
            field=models.CharField(default='InUse', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='mod_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='watchdog.PrivateIpAllocation'),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='mod_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prvip_mod_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
