# Generated by Django 2.1.7 on 2019-04-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0015_auto_20190401_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_access_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_client_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_client_num',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_cvlan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_device_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_down_brandwidth',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_gateway',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_ies',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_ip_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_link_tag',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_logic_port',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_mask',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_olt_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_product_num',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_svlan',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_up_brandwidth',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privateipallocation',
            name='alc_time',
            field=models.DateTimeField(),
        ),
    ]
