# Generated by Django 2.1.7 on 2019-04-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0016_auto_20190403_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_access_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_client_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_client_num',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_community',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_cvlan',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_device_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_gateway',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_ip_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_ipsegment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_logic_port',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_olt_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_product_num',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_rd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_rt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_service',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_service_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_svlan',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
