# Generated by Django 2.1.7 on 2019-04-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0017_auto_20190403_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateipmodrecord',
            name='ever_state',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='publicipmodrecord',
            name='ever_state',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
