# Generated by Django 2.1.7 on 2019-04-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0018_auto_20190403_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privateipallocation',
            options={'ordering': ['-alc_time']},
        ),
    ]
