# Generated by Django 2.1.7 on 2019-04-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0019_auto_20190403_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicIpSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_segment', models.GenericIPAddressField()),
                ('mask', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='publicipsegment',
            unique_together={('ip_segment', 'mask')},
        ),
    ]
