# Generated by Django 2.1.7 on 2019-04-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0020_auto_20190405_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicipmodrecord',
            name='record_time',
            field=models.DateTimeField(),
        ),
    ]
