# Generated by Django 2.1.7 on 2019-04-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0021_auto_20190409_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateipmodrecord',
            name='record_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='publicipallocation',
            name='alc_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publicipmodrecord',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
