# Generated by Django 2.1.7 on 2019-04-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0022_auto_20190409_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateipallocation',
            name='alc_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='privateipmodrecord',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
