# Generated by Django 2.1.7 on 2019-04-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0024_publicipsegment_segment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicipsegment',
            name='segment_type',
            field=models.IntegerField(choices=[(1, '公网外部使用'), (2, '公网内部使用'), (3, '私网')], default=1),
        ),
    ]
