# Generated by Django 2.1.7 on 2019-04-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0025_auto_20190419_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicipsegment',
            name='segment_type',
            field=models.IntegerField(choices=[(-1, '私网'), (1, '公网外部使用'), (2, '公网内部使用')], default=1),
        ),
    ]
