# Generated by Django 2.1.7 on 2019-02-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpmanResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('slot', models.CharField(max_length=4)),
                ('slot_type', models.CharField(max_length=40)),
                ('mda', models.CharField(max_length=4)),
                ('mda_type', models.CharField(max_length=40)),
                ('port', models.CharField(max_length=30)),
                ('brand_width', models.CharField(max_length=20)),
                ('port_status', models.CharField(max_length=10)),
                ('port_phy_status', models.CharField(max_length=10)),
                ('logic_port', models.CharField(max_length=20)),
                ('logic_port_description', models.TextField()),
                ('port_description', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ipmanresource',
            unique_together={('device_name', 'port')},
        ),
    ]
