# Generated by Django 2.1.7 on 2019-06-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zxclientinfo',
            name='guard_level',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
