# Generated by Django 2.1.7 on 2019-03-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ipmanresource',
            index=models.Index(fields=['slot'], name='networkreso_slot_aff53b_idx'),
        ),
        migrations.AddIndex(
            model_name='ipmanresource',
            index=models.Index(fields=['mda'], name='networkreso_mda_2a3d16_idx'),
        ),
    ]
