# Generated by Django 2.1.7 on 2019-07-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0002_zxclientinfo_guard_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=255, null=True)),
                ('client_name', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=5, null=True)),
                ('ip', models.CharField(max_length=200, null=True)),
                ('gateway', models.GenericIPAddressField(null=True)),
                ('bng', models.CharField(max_length=255, null=True)),
                ('logic_port', models.CharField(max_length=20, null=True)),
                ('svlan', models.PositiveIntegerField(default=0)),
                ('cevlan', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=255, null=True)),
                ('ip_func', models.CharField(max_length=4, null=True)),
                ('olt', models.CharField(max_length=255, null=True)),
                ('service_id', models.PositiveIntegerField(default=0)),
                ('brand_width', models.PositiveIntegerField(default=0)),
                ('group_id', models.PositiveIntegerField(default=0)),
                ('client_id', models.PositiveIntegerField(default=0)),
                ('network_type', models.CharField(max_length=5, null=True)),
                ('community', models.CharField(max_length=50, null=True)),
                ('rt', models.CharField(blank=True, max_length=50, null=True)),
                ('rd', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('alc_user', models.CharField(max_length=10, null=True)),
                ('alc_time', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='ipallocation',
            index=models.Index(fields=['ip'], name='networkreso_ip_0eb81d_idx'),
        ),
    ]
