# Generated by Django 2.1.7 on 2019-03-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0002_auto_20190310_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmanresource',
            name='mda',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='ipmanresource',
            name='slot',
            field=models.SmallIntegerField(),
        ),
    ]
