# Generated by Django 2.1.7 on 2019-03-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0003_auto_20190310_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iprecord',
            options={'ordering': ['id']},
        ),
    ]
