# Generated by Django 2.1.7 on 2019-07-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0004_auto_20190714_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipallocation',
            name='access_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
