# Generated by Django 2.1.7 on 2019-07-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0006_auto_20190715_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipallocation',
            options={'ordering': ['-alc_time']},
        ),
        migrations.AlterModelOptions(
            name='ipmod',
            options={'ordering': ['-mod_time']},
        ),
        migrations.AlterField(
            model_name='ipallocation',
            name='cevlan',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipallocation',
            name='svlan',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmod',
            name='cevlan',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ipmod',
            name='svlan',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
