# Generated by Django 2.1.7 on 2019-04-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0007_auto_20190404_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprecord',
            name='ip_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='Public', max_length=10),
            preserve_default=False,
        ),
    ]
