# Generated by Django 2.1.7 on 2019-07-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0007_auto_20190716_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateipmodrecord',
            name='mod_target',
        ),
        migrations.RemoveField(
            model_name='publicipmodrecord',
            name='mod_target',
        ),
        migrations.DeleteModel(
            name='PrivateIpAllocation',
        ),
        migrations.DeleteModel(
            name='PrivateIpModRecord',
        ),
        migrations.DeleteModel(
            name='PublicIpAllocation',
        ),
        migrations.DeleteModel(
            name='PublicIpModRecord',
        ),
    ]
