# Generated by Django 2.1.7 on 2019-04-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0008_iprecord_ip_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porterrordiff',
            options={'ordering': ['-record_time', '-id']},
        ),
    ]
