# Generated by Django 2.1.7 on 2019-04-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0009_auto_20190410_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprecord',
            name='ip_mask',
            field=models.IntegerField(null=True),
        ),
    ]
