# Generated by Django 2.1.7 on 2019-07-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0009_ipmod_mod_target_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipallocation',
            name='last_mod_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ipmod',
            name='mod_type',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
