# Generated by Django 2.1.7 on 2019-08-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0010_auto_20190729_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipallocation',
            name='ip_mask',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ipmod',
            name='ip_mask',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
