# Generated by Django 2.1.7 on 2019-04-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0010_iprecord_ip_mask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porterrordiff',
            options={'ordering': ['-id']},
        ),
    ]
