# Generated by Django 2.1.7 on 2019-04-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0011_auto_20190419_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprecord',
            name='ip_type',
            field=models.CharField(choices=[('private', 'Private'), ('public_outer', 'PublicOuter'), ('public_inner', 'PublicInner')], max_length=20),
        ),
    ]
