# Generated by Django 2.2.5 on 2019-10-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0011_auto_20190802_1459'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ipmanresource',
            name='networkreso_slot_aff53b_idx',
        ),
        migrations.RemoveIndex(
            model_name='ipmanresource',
            name='networkreso_mda_2a3d16_idx',
        ),
        migrations.RemoveIndex(
            model_name='ipmanresource',
            name='networkreso_logic_p_2b994b_idx',
        ),
        migrations.AddIndex(
            model_name='ipmanresource',
            index=models.Index(fields=['slot'], name='MR_REC_ipma_slot_bc9db5_idx'),
        ),
        migrations.AddIndex(
            model_name='ipmanresource',
            index=models.Index(fields=['mda'], name='MR_REC_ipma_mda_8b4fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='ipmanresource',
            index=models.Index(fields=['logic_port'], name='MR_REC_ipma_logic_p_3e1319_idx'),
        ),
        migrations.AlterModelTable(
            name='ipmanresource',
            table='MR_REC_ipman_resource',
        ),
    ]
