# Generated by Django 2.1.7 on 2019-05-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0012_auto_20190419_1434'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='iprecord',
            index=models.Index(fields=['device_ip'], name='networkreso_device__e13064_idx'),
        ),
    ]
