# Generated by Django 2.1.7 on 2019-05-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0013_auto_20190521_2146'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='porterrordiff',
            index=models.Index(fields=['device_name'], name='networkreso_device__0451ee_idx'),
        ),
    ]
