# Generated by Django 2.1.7 on 2019-05-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0014_auto_20190523_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortPerf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=30)),
                ('tx_now_power', models.FloatField()),
                ('tx_high_warm', models.FloatField()),
                ('tx_low_warm', models.FloatField()),
                ('tx_state', models.IntegerField()),
                ('rx_now_power', models.FloatField()),
                ('rx_high_warm', models.FloatField()),
                ('rx_low_warm', models.FloatField()),
                ('rx_state', models.IntegerField()),
                ('utility_in', models.FloatField()),
                ('utility_out', models.FloatField()),
                ('record_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-record_time'],
            },
        ),
        migrations.AddIndex(
            model_name='portperf',
            index=models.Index(fields=['device_name'], name='networkreso_device__6a8a33_idx'),
        ),
        migrations.AddIndex(
            model_name='portperf',
            index=models.Index(fields=['port'], name='networkreso_port_d544a3_idx'),
        ),
    ]
