# Generated by Django 2.2.5 on 2019-11-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0015_auto_20191122_1446'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='iprecord',
            index=models.Index(fields=['device_name'], name='MR_REC_ip_r_device__6cbea1_idx'),
        ),
        migrations.AddIndex(
            model_name='oltbngref',
            index=models.Index(fields=['bng'], name='MR_REP_olt__bng_848536_idx'),
        ),
        migrations.AddIndex(
            model_name='oltbngref',
            index=models.Index(fields=['logic_port'], name='MR_REP_olt__logic_p_def22d_idx'),
        ),
    ]
