# Generated by Django 2.1.7 on 2019-05-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0015_auto_20190523_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZxClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(null=True)),
                ('client_name', models.CharField(max_length=255, null=True)),
                ('product_id', models.IntegerField(null=True)),
                ('device1', models.CharField(max_length=255, null=True)),
                ('device1_port', models.CharField(max_length=40, null=True)),
                ('device2', models.CharField(max_length=255, null=True)),
                ('device2_port', models.CharField(max_length=40, null=True)),
                ('gateway', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('ip', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='zxclientinfo',
            index=models.Index(fields=['ip'], name='networkreso_ip_ac310d_idx'),
        ),
    ]
