# Generated by Django 2.2.5 on 2019-11-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0016_auto_20191125_1424'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='oltbngref',
            index=models.Index(fields=['olt_num'], name='MR_REP_olt__olt_num_054b99_idx'),
        ),
    ]
