# Generated by Django 2.1.7 on 2019-05-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0016_auto_20190523_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zxclientinfo',
            name='group_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zxclientinfo',
            name='product_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
