# Generated by Django 2.2.5 on 2019-12-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0017_auto_20191126_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclientipsegment',
            name='ip_state',
            field=models.SmallIntegerField(default=0),
        ),
    ]
