# Generated by Django 2.1.7 on 2019-05-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0017_auto_20190523_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprecord',
            name='logic_port_num',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
