# Generated by Django 2.1.7 on 2019-05-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0018_iprecord_logic_port_num'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ipmanresource',
            index=models.Index(fields=['logic_port'], name='networkreso_logic_p_2b994b_idx'),
        ),
        migrations.AddIndex(
            model_name='iprecord',
            index=models.Index(fields=['logic_port_num'], name='networkreso_logic_p_570a28_idx'),
        ),
    ]
