# Generated by Django 2.1.7 on 2019-05-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0019_auto_20190524_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porterrordiff',
            name='port',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='portperf',
            name='port',
            field=models.CharField(max_length=40),
        ),
    ]
