# Generated by Django 2.2.5 on 2019-12-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0020_groupclientipreserve_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclientipreserve',
            name='client_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groupclientipreserve',
            name='contact',
            field=models.CharField(max_length=11),
        ),
    ]
