# Generated by Django 2.1.7 on 2019-05-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0020_auto_20190525_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprecord',
            name='gateway',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
