# Generated by Django 2.1.7 on 2019-05-29 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0021_iprecord_gateway'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortErrorDiff',
        ),
    ]
