# Generated by Django 3.0.1 on 2020-03-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0022_auto_20200102_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicipsegment',
            old_name='ip_segment',
            new_name='upper_segment',
        ),
        migrations.AddField(
            model_name='publicipsegment',
            name='specialization',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='publicipsegment',
            name='upper_mask',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='publicipsegment',
            unique_together={('upper_segment', 'upper_mask')},
        ),
        migrations.AlterModelTable(
            name='publicipsegment',
            table='MR_REC_public_segment_reference',
        ),
        migrations.RemoveField(
            model_name='publicipsegment',
            name='mask',
        ),
        migrations.RemoveField(
            model_name='publicipsegment',
            name='segment_type',
        ),
    ]
