# Generated by Django 2.1.7 on 2019-05-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0022_delete_porterrordiff'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprecord',
            name='ip_func',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
