# Generated by Django 3.0.1 on 2020-03-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0025_auto_20200310_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicipsegmentschema',
            name='state',
            field=models.SmallIntegerField(default=0),
        ),
    ]
