# Generated by Django 3.0.1 on 2020-03-24 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0027_auto_20200315_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmod',
            name='icp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networkresource.ICP'),
        ),
    ]
