# Generated by Django 3.0.5 on 2020-04-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networkresource', '0030_groupclientipreserve_expire_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicipsegmentschema',
            name='upper_mask',
        ),
        migrations.RemoveField(
            model_name='publicipsegmentschema',
            name='upper_segment',
        ),
        migrations.AddField(
            model_name='publicipsegmentschema',
            name='belong_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networkresource.PublicIpSegment'),
        ),
    ]
