# Generated by Django 3.0.5 on 2020-04-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0002_auto_20191028_0943'),
        ('networkresource', '0031_auto_20200428_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicipsegmentschema',
            name='access_bng',
        ),
        migrations.AddField(
            model_name='publicipsegmentschema',
            name='access_bng',
            field=models.ManyToManyField(to='watchdog.Device'),
        ),
        migrations.RemoveField(
            model_name='publicipsegmentschema',
            name='access_olt',
        ),
        migrations.AddField(
            model_name='publicipsegmentschema',
            name='access_olt',
            field=models.ManyToManyField(to='networkresource.OltInfoWG'),
        ),
    ]
